---
sidebar: sidebar 
permalink: dbops/hybrid-dbops-sc-prereq-cloud.html 
summary: 在安装 Cloud Manager 连接器和Cloud Volumes ONTAP并配置SnapMirror之前，我们必须为我们的云环境进行一些准备。本页介绍了部署Cloud Volumes ONTAP时需要完成的工作以及注意事项。 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 公共云的先决条件
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在安装 Cloud Manager 连接器和Cloud Volumes ONTAP并配置SnapMirror之前，我们必须为我们的云环境进行一些准备。本页介绍了部署Cloud Volumes ONTAP时需要完成的工作以及注意事项。



== Cloud Manager 和Cloud Volumes ONTAP部署前提条件清单

* NetApp Cloud Central 登录
* 通过 Web 浏览器访问多个端点的网络
* 连接器的网络位置
* 云提供商权限
* 个人服务网络


有关入门所需内容的更多信息，请访问我们的 https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["云文档"^]。



== 注意事项



=== 1.什么是 Cloud Manager 连接器？

大多数情况下，Cloud Central 帐户管理员必须在您的云或本地网络中部署连接器。该连接器使 Cloud Manager 能够管理公共云环境中的资源和流程。

有关连接器的更多信息，请访问我们的 https://docs.netapp.com/us-en/occm/concept_connectors.html["云文档"^]。



=== 2.Cloud Volumes ONTAP 的大小和架构

部署Cloud Volumes ONTAP时，您可以选择预定义包或创建自己的配置。尽管其中的许多值可以在以后无中断地进行更改，但在部署之前需要根据要在云中部署的工作负载做出一些关键决策。

每个云提供商都有不同的部署选项，并且几乎每个工作负载都有其独特的属性。  NetApp拥有 https://bluexp.netapp.com/calculator-hub["TCO计算器"^]它可以帮助根据容量和性能正确确定部署规模，但它是围绕一些值得考虑的基本概念构建的：

* 所需容量
* 云虚拟机的网络能力
* 云存储的性能特点


关键是要规划一个不仅能满足当前容量和性能要求，而且还能考虑未来增长的配置。这通常被称为容量余量和性能余量。

如果您想了解更多信息，请阅读有关正确规划的文档 https://docs.netapp.com/us-en/occm/task_planning_your_config.html["AWS"^]， https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure"^] ， 和 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^]。



=== 3.单节点还是高可用性？

在所有云中，都可以选择在单个节点或具有两个节点的集群高可用性对中部署 CVO。根据使用情况，您可能希望部署单个节点以节省成本或部署 HA 对以提供进一步的可用性和冗余。

对于 DR 用例或为开发和测试启动临时存储，单节点很常见，因为突然的区域或基础设施中断的影响较低。但是，对于任何生产用例，当数据仅位于单个位置时，或者当数据集必须具有更多冗余和可用性时，建议使用高可用性。

有关每个云版本的高可用性架构的更多信息，请访问 https://docs.netapp.com/us-en/occm/concept_ha.html["AWS"^]， https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure"^]和 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^]。
