---
sidebar: sidebar 
permalink: automation/getting-started-requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 本页介绍在NetApp ONTAP存储上部署 Oracle19c 的自动化方法。 
---
= 入门
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
该解决方案设计为在 AWX/Tower 环境中运行或通过 Ansible 控制主机上的 CLI 运行。



== AWX/塔

对于 AWX/Tower 环境，将指导您创建ONTAP集群管理和 Oracle 服务器（IP 和主机名）的清单、创建凭据、配置从NetApp Automation Github 中提取 Ansible 代码的项目以及启动自动化的作业模板。

. 填写特定于您的环境的变量，然后将其复制并粘贴到作业模板中的 Extra Vars 字段中。
. 将额外的变量添加到您的作业模板后，您就可以启动自动化。
. 作业模板通过指定 ontap_config、linux_config 和 oracle_config 的标签分三个阶段运行。




== 通过 Ansible 控制主机的 CLI

. 配置 Linux 主机，以便将其用作 Ansible 控制主机link:https://docs.netapp.com/us-en/netapp-solutions-dataops/automation/getting-started.html["点击此处查看详细说明"^]
. 配置 Ansible 控制主机后，您可以 git clone Ansible Automation 存储库。
. 使用ONTAP集群管理的 IP 和/或主机名以及 Oracle 服务器的管理 IP 编辑 hosts 文件。
. 填写特定于您的环境的变量，然后将其复制并粘贴到 `vars.yml`文件。
. 每个 Oracle 主机都有一个由其主机名标识的变量文件，其中包含特定于主机的变量。
. 所有变量文件完成后，您可以通过指定标签分三个阶段运行剧本 `ontap_config`， `linux_config` ， 和 `oracle_config`。




== 要求

[cols="3, 9"]
|===
| 环境 | 要求 


.4+| Ansible 环境 | AWX/Tower 或 Linux 主机作为 Ansible 控制主机 


| Ansible v.2.10 及更高版本 


| Python 3 


| Python 库 - netapp-lib - xmltodict - jmespath 


.3+| ONTAP | ONTAP版本 9.3 - 9.7 


| 两个数据聚合 


| NFS vlan 和 ifgrp 创建 


.5+| Oracle 服务器 | RHEL 7/8 


| Oracle Linux 7/8 


| NFS、公共和可选管理的网络接口 


| Oracle 服务器上的 Oracle 安装文件 
|===


== 自动化详细信息

此自动化部署采用由三个独立角色组成的单个 Ansible 剧本设计。这些角色适用于ONTAP、Linux 和 Oracle 配置。下表描述了正在自动化的任务。

[cols="4, 9"]
|===
| 角色 | Tasks 


.5+| ontap_config | ONTAP环境的预检查 


| 为 Oracle 创建基于 NFS 的 SVM 


| 制定出口政策 


| 为 Oracle 创建卷 


| 创建 NFS LIF 


.9+| *linux_配置* | 创建挂载点并挂载 NFS 卷 


| 验证 NFS 挂载 


| 操作系统特定配置 


| 创建 Oracle 目录 


| 配置大页面 


| 禁用 SELinux 和防火墙守护进程 


| 启用并启动 chronyd 服务 


| 增加文件描述符的硬限制 


| 创建 pam.d 会话文件 


.8+| *oracle_配置* | Oracle软件安装 


| 创建 Oracle 监听器 


| 创建 Oracle 数据库 


| Oracle环境配置 


| 保存 PDB 状态 


| 启用实例存档模式 


| 启用 DNFS 客户端 


| 在操作系统重启之间启用数据库自动启动和关闭 
|===


== 默认参数

为了简化自动化，我们预设了许多必需的 Oracle 部署参数并设置了默认值。对于大多数部署来说，通常不需要更改默认参数。更高级的用户可以谨慎地更改默认参数。默认参数位于 defaults 目录下的每个角色文件夹中。



== 部署说明

开始之前，请下载以下 Oracle 安装和补丁文件，并将它们放在 `/tmp/archive`每个要部署的数据库服务器上的所有用户均具有读、写和执行访问权限的目录。自动化任务在该特定目录中查找命名的安装文件以进行 Oracle 安装和配置。

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== 许可证

您应该阅读 Github 存储库中所述的许可证信息。通过访问、下载、安装或使用此存储库中的内容，您同意所列出的许可条款link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["此处"^]。

请注意，制作和/或共享此存储库中的内容的任何衍生作品都受到某些限制。请务必阅读link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["许可证"^]在使用内容之前。如果您不同意所有条款，请不要访问、下载或使用此存储库中的内容。

准备好后，单击link:awx-automation.html["点击此处查看 AWX/Tower 部署的详细步骤"]或者link:cli-automation.html["此处用于 CLI 部署"]。
